### ISSUE TITLE
RPM generators errors are ignored

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpm#1183]
From https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/JWCV2PG2EG5TCPMJAHWM7B54SMHT6A4V/

And from https://koji.fedoraproject.org/koji/buildinfo?buildID=1495361

The upstream version is "weird". The RPM dist generator fails with:

```
Traceback (most recent call last):
  File "/usr/lib/rpm/pythondistdeps.py", line 379, in <module>
    spec_list.append(convert(name, spec[0], spec[1]))
  File "/usr/lib/rpm/pythondistdeps.py", line 125, in convert
    return OPERATORS[operator](name, operator, version_id)
  File "/usr/lib/rpm/pythondistdeps.py", line 79, in convert_equal
    return '{} = {}'.format(name, version)
  File "/usr/lib/rpm/pythondistdeps.py", line 47, in __str__
    while self.version[-1] == 0:
IndexError: list index out of range
```

The builds goes on.

There are 3 things I'd like to see fixed:

 - the traceback should say: `Cannot process Python package version: 0+unknown`
 - the build should abort on errors
 - the version is [actually valid](https://www.python.org/dev/peps/pep-0440/#local-version-identifiers)

**Comment by hroncok** [comment]
cc @torsava @gordonmessmer

**Comment by hroncok** [comment]
It seems that it's not the local version modifier that breaks this, but version `0`. See https://github.com/fedora-python/pyp2rpm/pull/233

**Comment by torsava** [comment]
Addressed here: https://github.com/rpm-software-management/rpm/pull/1184

**Comment by hroncok** [comment]
That fixes the particular problem. But the two remaining points still stand:

 - the exception when the conversion fails is not telling anything useful
 - the rpmbuild continues (can we abort the build from a dependency generator?)

**Comment by ignatenkobrain** [comment]
> the rpmbuild continues (can we abort the build from a dependency generator?)

Well, this is how it is done for all depgens, so this would be RFE on its own.

**Comment by hroncok** [comment]
Thanks.

**Comment by torsava** [comment]
> the exception when the conversion fails is not telling anything useful

As this was an unexpected error, we don't know at what point in the code the next unexpected error would strike. So the way I see it we would have to wrap the whole machinery in `try..except` which isn't great, or do you propose a different solution, @hroncok ?

**Comment by pmatilai** [comment]
Yup, the generator failure handling is a funny mess:
- in legacy generators (the "external generator") only provide generation can cause build-failure
- in current generators, all script error codes are ignored
- ...except for buildrequires generator where script errors cause build failure

Of course the only sane thing is to always fail on non-zero return, with maybe a macro override to allow temporarily working around bugs etc.

**Comment by hroncok** [comment]
The almost-backwards-compatible way would be to have a specific exit code that should abort the build. E.g. "exit with 66 to abort the build".

Technically, I think it is possible to abort the build by generating an invalid dependency, but that is hardly an API.

**Comment by hroncok** [comment]
@torsava OK, let's wait for the next unexpected error. But wrapping everything in try-except and failing with useful error message is not a bad idea.

**Comment by torsava** [comment]
> @torsava OK, let's wait for the next unexpected error. But wrapping everything in try-except and failing with useful error message is not a bad idea.

Ok, I'll add it to my PR.

**Comment by torsava** [comment]
> There are 3 things I'd like to see fixed:
> 
> * the traceback should say: `Cannot process Python package version: 0+unknown`
> * the build should abort on errors
> * the version is [actually valid](https://www.python.org/dev/peps/pep-0440/#local-version-identifiers)

First and last issue have been fixed in https://github.com/rpm-software-management/rpm/pull/1242.

What remains is that the build should abort on errors.

**Comment by pmatilai** [comment]
Reopening as the fix was reverted (it was just too broken to live)

**Comment by soig** [comment]
For references, here's the fallout:
https://github.com/rpm-software-management/rpm/issues/1285

**Comment by pmatilai** [comment]
Yup, and there's more: every caller of rpmfcExec() does so with slightly different expectations of what will happen in what situations, and rpmfcHelper() was doing +1 on errors whereas the lower layers were returning -1 and ... whatnot. It needs a *careful* review on reapproach.

**Comment by decathorpe** [comment]
I'm working on updating the generators for Rust crates, and I came across the same problem. Sometimes the package spec is out of date with the upstream project's metadata, which triggers errors during generation of Provides and Requires and results in packages with broken metadata. I now pushed the same workaround as the Python macros (i.e. output a string that's not a valid RPM identifier), but that's not really ideal.

**Comment by pmatilai** [comment]
Besides stopping the build, it should emit the exact command that was executing when it failed.
