### ISSUE TITLE
AttributeError in cnf

### ISSUE THREAD

**Issue by gantsevdenis** [rpm-software-management/rpm#1651]
Not sure if this relates to `cnf` or to `rpm`.
Since `cnf` is just the frontend, I post it here:

```
denis@localhost:~/sources/rpm> cnf blabla
 blabla: command not found

denis@localhost:~/sources/rpm> cnf useradd
useradd: searching ... Traceback (most recent call last):
  File "/usr/bin/cnf", line 132, in <module>
    main()
  File "/usr/bin/cnf", line 99, in main
    pkg = find_package_by_file(path + '/' + term)
  File "/usr/bin/cnf", line 82, in find_package_by_file
    return next(mi)['name'].decode()
AttributeError: 'str' object has no attribute 'decode'

denis@localhost:~/sources/rpm> zypper info command-not-found
Loading repository data...
Reading installed packages...


Information for package command-not-found:
------------------------------------------
Repository     : openSUSE-Tumbleweed-Oss
Name           : command-not-found
Version        : 0.2.4+20210325.6c2d9f3-1.1
Arch           : noarch
Vendor         : openSUSE
Installed Size : 119.3 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : scout-0.2.4+20210325.6c2d9f3-1.1.src
Summary        : Command Not Found extension for shell

denis@localhost:~/sources/rpm> zypper info rpm
Loading repository data...
Reading installed packages...

Information for package rpm:
----------------------------
Repository     : openSUSE-Tumbleweed-Oss
Name           : rpm
Version        : 4.16.1.3-1.2
Arch           : x86_64
Vendor         : openSUSE
Installed Size : 2.7 MiB
Installed      : Yes
Status         : up-to-date
Source package : rpm-4.16.1.3-1.2.src
```

**Comment by pmatilai** [comment]
It's a cnf issue, it assumes python bindings return header data as binary but since rpm >= 4.15 string data is returned as native Python strings (see https://rpm.org/wiki/Releases/4.15.0)
